### ISSUE TITLE
Two search boxes on one page in Gatsby apps don't work correctly

### ISSUE THREAD

**Issue by don-esteban** [apps-360/site-search-360-react#3]
Placing two search boxes on one page in a Gatsby app don't work correctly. I did a minimal bug reproduction and propose a solution.

See: https://github.com/don-esteban/for-jaro

TL;TR

Missing `componentWillUnmount` lifecycle method

```
componentWillUnmount() {
	const ss360Script = document.getElementById('ss360-script')
	if (ss360Script) {
		ss360Script.remove()
		delete window.initializeSs360
	}
}
```

**Comment by JVankat** [comment]
I did take a different approach (since reloading the script should not be necessary) - I've fixed this within our generic js plugin, but had to upgrade this component to our v14 script (mainly some minor style changes for search suggestions), since the v13 isn't being maintained anymore.

Can you please try to update the plugin to the **0.3.1** version and see whether this solves the issue for you? It did work as expected for me.

**Comment by don-esteban** [comment]
Thanks. The new component works as expected in our production site.

**Comment by don-esteban** [comment]
Nope, not really. Now, the issue has gone using the search button. Using Enter key produces still two inputs. I published a new bug reproduction version. Observe the config.

**Comment by JVankat** [comment]
A quick fix would be using a copy of the ss360Config and giving an alias to both checkboxes:

```
<SiteSearch360 siteId={SITE_ID} ss360Config={JSON.parse(JSON.stringify(ss360Config))} alias="sb1" />
<SiteSearch360 siteId={SITE_ID} ss360Config={JSON.parse(JSON.stringify(ss360Config))} alias="sb2" />
```

I'll take a look whether we can improve this behavior on our side.

**Comment by don-esteban** [comment]
I'll wait a few days. It's already a work around on production page, using only one search box. We can live with that for some days more.

**Comment by JVankat** [comment]
Please retest (and make sure the v14.1.85 is loading for you --> clearing the cache might be necessary).

**Comment by JVankat** [comment]
You need to check the developer console to see what script version exactly is being loaded. This was fixed in the js plugin, not within this component.

**Comment by don-esteban** [comment]
I see, browser cache, thought about Gatsby's cache. Seems like working now. But let me do a production check tomorrow. I'll close the issue, if it works in production.

**Comment by don-esteban** [comment]
Does work as expected. Thanks.
