### ISSUE TITLE
site-search-360-react loads multiple times in Gatsby apps. Missing cleanup code?

### ISSUE THREAD

**Issue by don-esteban** [apps-360/site-search-360-react#5]
Visit [https://www.software-express.de/](https://www.software-express.de/) and open Developer Tools

<img width="996" alt="Bildschirmfoto 2022-04-28 um 18 44 03" src="https://user-images.githubusercontent.com/6874584/165815112-c07fd4c8-31c6-4599-b802-36abc09db624.png">

Now visit other page. Each page appends new loaders/themes.

<img width="1037" alt="Bildschirmfoto 2022-04-28 um 18 47 43" src="https://user-images.githubusercontent.com/6874584/165815594-e162a322-f80c-47a9-a458-fc28e699ea2f.png">

**Comment by JVankat** [comment]
Fixed in v14.1.95, please make sure to clear the cache and that the latest version is loading before retesting.

![image](https://user-images.githubusercontent.com/9029472/168094388-ddb83801-23fa-487e-8a96-049a28a5fb70.png)
